@startuml
actor "Admin/PM" as User

participant "U I" as UI
participant "Authorization Service"
participant "Project Group Service" as System
participant "Database" as DB

User -> UI: Nhập thông tin nhóm dự án và xác nhận tạo nhóm
activate UI

UI -> "Authorization Service": Kiểm tra quyền truy cập
activate "Authorization Service"

"Authorization Service" --> UI: Quyền hợp lệ
deactivate "Authorization Service"

UI -> System: Gửi yêu cầu tạo nhóm dự án
activate System

System -> DB: Kiểm tra trùng lặp tên nhóm
activate DB

alt Tên nhóm chưa tồn tại
    DB --> System: Cho phép tạo nhóm

    System -> DB: Lưu nhóm dự án vào cơ sở dữ liệu
    DB --> System: Lưu thành công
    deactivate DB


    System --> UI: Xác nhận nhóm dự án tạo thành công
    deactivate System
    UI --> User: Hiển thị nhóm dự án mới

else Tên nhóm đã tồn tại
    DB --> System: Lỗi - Nhóm dự án đã tồn tại
    deactivate DB
    System --> UI: Hiển thị lỗi "Nhóm dự án đã tồn tại"
    UI --> User: Hiển thị lỗi "Nhóm dự án đã tồn tại"
    deactivate System
end

@enduml
